# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Fr3nezy.PolyLoupe
PackageVersion: 0.1.1
InstallerType: inno
Scope: machine
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
FileExtensions:
  - glb
  - gltf
  - fbx
  - obj
  - stl
  - ply
  - 3mf
  - dae
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Fr3nezy/polyloupe/releases/download/v0.1.1/PolyLoupe-Setup-0.1.1.exe
    InstallerSha256: 8D48FE57EFCCE6DA870A7D0D4C27D501C31EC9E12E37D3EFCB960F953C87964A
ManifestType: installer
ManifestVersion: 1.6.0
