# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Fr3nezy.PolyLoupe
PackageVersion: 0.1.0
InstallerType: inno
Scope: machine
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
FileExtensions:
  - glb
  - gltf
  - fbx
  - obj
  - stl
  - ply
  - 3mf
  - dae
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Fr3nezy/polyloupe/releases/download/v0.1.0/PolyLoupe-Setup-0.1.0.exe
    InstallerSha256: D42772E0CDDBDA758446457D983B5A3737F16481924EE2B4D5BFABEDA029E557
ManifestType: installer
ManifestVersion: 1.6.0
